apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: hlf-channel-anchors
data:
{{- range $i, $channel := .Values.network.channels }}
{{- range $org := $channel.orgs }}
  {{ $channel.name }}-{{ $org }}.tx: |-
      {{ $.Files.Get (printf "channel-artifacts/%s/%sMSPanchors.tx" $channel.name $org) | b64enc }}
{{- end }} {{- /* channel.orgs */ -}}
{{- end }} {{- /* network.channels */ -}}
