{{ $orderer := (printf "hlf-orderer--%s" (index .Values.OrdererOrgs 0).Name | lower) }} 
{{ $vars:= dict}}

apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  # name: hlf-chaincodes
  generateName: hlf-chaincodes-
spec:
  entrypoint: chaincodes
  volumes:

{{- range $i, $org := .Values.PeerOrgs }}
{{- $peerStartIndex := (not $org.Template.Start) | ternary 0 $org.Template.Start | int }}
{{- range $peerIndex := untilStep $peerStartIndex (add $peerStartIndex $org.Template.Count | int) 1 }}
{{- $peer := (printf "peer%s" ($peerIndex | toString)) }}

  - name: peer-{{ $org.Name | lower }}-{{ $peer | lower }}-tls
    secret:
      secretName: hlf-peer--{{ $org.Name | lower }}--{{ $peer | lower }}-tls
  - name: peer-{{ $org.Name | lower }}-{{ $peer | lower }}-admin-msp
    secret:
      secretName: hlf-peer--{{ $org.Name | lower }}--{{ $peer | lower }}-admin-msp
      items:
      - key: cert.pem
        path: signcerts/cert.pem
      - key: key.pem
        path: keystore/key.pem
      - key: cacert.pem
        path: cacerts/cert.pem
      - key: tlscacert.pem
        path: tlscacerts/cert.pem
      - key: admincert.pem
        path: admincerts/cert.pem
      
{{- end }} {{- /* Peers */ -}}
{{- end }} {{- /* Orgs */ -}}{{""}}

  # chaincodes configMaps
  {{- range $i, $chaincode := $.Values.network.chaincodes }}    
  {{- if or (not $.Values.flow.chaincode.include) (has $chaincode.name $.Values.flow.chaincode.include) }}
  - name: chaincode-{{ $chaincode.name | lower }}
    configMap:
      name: hlf-chaincode--{{ $chaincode.name | lower }}
  {{- end }} {{- /* if chaincode included */ -}}
  {{- end }}

  templates:
  - name: chaincodes
    steps:
# top level: chaincodes
{{- $_ := set $vars "firstStep" true }}
{{- range $i, $chaincode := .Values.network.chaincodes }}
{{- if or (not $.Values.flow.chaincode.include) (has $chaincode.name $.Values.flow.chaincode.include) }}
{{- if or $vars.firstStep (not $.Values.flow.chaincode.parallel) }}
    - 
{{- end }}
      - name: chaincode--{{ $chaincode.name }}
        template: chaincode--{{ $chaincode.name }}
{{- $_ := set $vars "firstStep" false }}
{{- end }} {{- /* if chaincode included */ -}}
{{- end }} {{- /* chaincodes */ -}}{{""}}

# second level: chaincode templates
{{- range $i, $chaincode := .Values.network.chaincodes }}
{{- if or (not $.Values.flow.chaincode.include) (has $chaincode.name $.Values.flow.chaincode.include) }}
  - name: chaincode--{{ $chaincode.name }}
    steps:
    {{- if $.Values.flow.install.enabled }}
    - - name: install-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}
        template: install-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}
    {{- end }}
    {{- if $.Values.flow.instantiate.enabled }}
    - - name: instantiate-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}
        template: instantiate-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}
    {{- end }}
    {{- if $.Values.flow.upgrade.enabled }}
    - - name: upgrade-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}
        template: upgrade-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}
    {{- end }}
    {{- if $.Values.flow.invoke.enabled }}
    - - name: invoke-chaincode--{{ $chaincode.name }}
        template: invoke-chaincode--{{ $chaincode.name }}
    {{- end }}
{{- end }} {{- /* if chaincode included */ -}}
{{- end }} {{- /* chaincodes */ -}}{{""}}

# third level: install chaincode templates
{{- if $.Values.flow.install.enabled }}
{{- range $i, $chaincode := .Values.network.chaincodes }}
{{- if or (not $.Values.flow.chaincode.include) (has $chaincode.name $.Values.flow.chaincode.include) }}
{{- $_ := set $vars "firstStep" true }}
  - name: install-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}
    steps:
     
{{- range $orgName := $chaincode.orgs }}
{{- range $i, $org := $.Values.PeerOrgs }}

{{- if eq $orgName $org.Name }}

{{- $peerStartIndex := (not $org.Template.Start) | ternary 0 $org.Template.Start | int }}
{{- range $peerIndex := untilStep $peerStartIndex (add $peerStartIndex $org.Template.Count | int) 1 }}
{{- $peer := (printf "peer%s" ($peerIndex | toString)) }}
{{- if or $vars.firstStep (not $.Values.flow.install.parallel) }}
    - 
{{- end }}
      - name: install-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}--{{ $org.Name }}--{{ $peer }}
        template: install-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}--{{ $org.Name }}--{{ $peer }}
{{- $_ := set $vars "firstStep" false }}
{{- end }} {{- /* peerIndex */ -}} 
{{- end }} {{- /* if org */ -}} 
{{- end }} {{- /* peer.Orgs */ -}}
{{- end }} {{- /* chaincode.orgs */ -}}
{{- end }} {{- /* if chaincode included */ -}}
{{- end }} {{- /* chaincodes */ -}}
{{- end }} {{- /* if flow.install.enabled */ -}}{{""}}

# third level: instantiate chaincode templates
{{- if $.Values.flow.instantiate.enabled }}

{{- range $i, $chaincode := .Values.network.chaincodes }}
{{- if or (not $.Values.flow.chaincode.include) (has $chaincode.name $.Values.flow.chaincode.include) }}
{{- $_ := set $vars "firstStep" true }}
  - name: instantiate-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}
    steps:
{{- range $channel := $chaincode.channels }}
{{- $orgName := index $channel.orgs 0 }}

{{- range $i, $org := $.Values.PeerOrgs }}

{{- if eq $orgName $org.Name }}

{{- $peerStartIndex := (not $org.Template.Start) | ternary 0 $org.Template.Start | int }}
{{- $peer := (printf "peer%s" ($peerStartIndex | toString)) }}
{{- if or $vars.firstStep (not $.Values.flow.instantiate.parallel) }}
    - 
{{- end }}
      - name: instantiate-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}--{{ $channel.name }}--{{ $org.Name }}--{{ $peer }}
        template: instantiate-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}--{{ $channel.name  }}--{{ $org.Name }}--{{ $peer }}

{{- $_ := set $vars "firstStep" false }}
{{- end }} {{- /* if org */ -}} 
{{- end }} {{- /* peer.Orgs */ -}}
{{- end }} {{- /* chaincode.channels */ -}}
{{- end }} {{- /* if chaincode included */ -}}
{{- end }} {{- /* chaincodes */ -}}
{{- end }} {{- /* if flow.instantiate.enabled */ -}}{{""}}

# third level: upgrade chaincode templates
{{- if $.Values.flow.upgrade.enabled }}

{{- range $i, $chaincode := .Values.network.chaincodes }}
{{- if or (not $.Values.flow.chaincode.include) (has $chaincode.name $.Values.flow.chaincode.include) }}
{{- $_ := set $vars "firstStep" true }}
  - name: upgrade-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}
    steps:
{{- range $channel := $chaincode.channels }}
{{- $orgName := index $channel.orgs 0 }}

{{- range $i, $org := $.Values.PeerOrgs }}

{{- if eq $orgName $org.Name }}

{{- $peerStartIndex := (not $org.Template.Start) | ternary 0 $org.Template.Start | int }}
{{- $peer := (printf "peer%s" ($peerStartIndex | toString)) }}
{{- if or $vars.firstStep (not $.Values.flow.instantiate.parallel) }}
    - 
{{- end }}
      - name: upgrade-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}--{{ $channel.name }}--{{ $org.Name }}--{{ $peer }}
        template: upgrade-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}--{{ $channel.name  }}--{{ $org.Name }}--{{ $peer }}

{{- $_ := set $vars "firstStep" false }}
{{- end }} {{- /* if org */ -}} 
{{- end }} {{- /* peer.Orgs */ -}}
{{- end }} {{- /* chaincode.channels */ -}}
{{- end }} {{- /* if chaincode included */ -}}
{{- end }} {{- /* chaincodes */ -}}
{{- end }} {{- /* if flow.instantiate.enabled */ -}}{{""}}

# third level: invoke chaincode templates
{{- if $.Values.flow.invoke.enabled }}

{{- range $i, $chaincode := .Values.network.chaincodes }}
{{- if or (not $.Values.flow.chaincode.include) (has $chaincode.name $.Values.flow.chaincode.include) }}
{{- $_ := set $vars "firstStep" true }}
  - name: invoke-chaincode--{{ $chaincode.name }}
    steps:
{{- range $channel := $chaincode.channels }}
{{- range $orgName := $channel.orgs }}
{{- range $i, $org := $.Values.PeerOrgs }}

{{- if eq $orgName $org.Name }}

{{- $peerStartIndex := (not $org.Template.Start) | ternary 0 $org.Template.Start | int }}
{{- range $peerIndex := untilStep $peerStartIndex (add $peerStartIndex $org.Template.Count | int) 1 }}
{{- $peer := (printf "peer%s" ($peerIndex | toString)) }}

{{- if or $vars.firstStep (not $.Values.flow.invoke.parallel) }}
    - 
{{- end }}
      - name: invoke-chaincode--{{ $chaincode.name }}--{{ $channel.name }}--{{ $org.Name }}--{{ $peer }}
        template: invoke-chaincode--{{ $chaincode.name }}--{{ $channel.name }}--{{ $org.Name }}--{{ $peer }}

{{- $_ := set $vars "firstStep" false }}
{{- end }} {{- /* peerIndex */ -}} 
{{- end }} {{- /* if org */ -}} 
{{- end }} {{- /* peer.Orgs */ -}}
{{ end }} {{- /* channel.orgs */ -}}
{{- end }} {{- /* chaincode.channels */ -}}
{{- end }} {{- /* if chaincode included */ -}}
{{- end }} {{- /* chaincodes */ -}}
{{- end }} {{- /* if flow.invoke.enabled */ -}}{{""}}

# leaf install templates
{{- if $.Values.flow.install.enabled }}
{{- range $i, $chaincode := .Values.network.chaincodes }}
{{- if or (not $.Values.flow.chaincode.include) (has $chaincode.name $.Values.flow.chaincode.include) }}
{{- range $orgName := $chaincode.orgs }}
{{- range $i, $org := $.Values.PeerOrgs }}

{{- if eq $orgName $org.Name }}

{{- $peerStartIndex := (not $org.Template.Start) | ternary 0 $org.Template.Start | int }}
{{- range $peerIndex := untilStep $peerStartIndex (add $peerStartIndex $org.Template.Count | int) 1 }}
{{- $peer := (printf "peer%s" ($peerIndex | toString)) }}

  - name: install-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}--{{ $org.Name }}--{{ $peer }}
    # chaincode: {{ $chaincode.name }}
    # org: {{ $org.Name }}
    # peer: {{ $peer }}
    inputs:
    retryStrategy:
      limit: {{ $.Values.retryCount }}
    container:
      image: hyperledger/fabric-peer:{{ $.Values.hyperledgerVersion }}
      # chaincode is packed with tar, first extract it
      command: ["sh", "-c", "mkdir -p /chaincode && \
                             tar -xf /hlf_config/chaincode/{{ $chaincode.name }}.tar -C /chaincode && \ 
                             peer chaincode install -p /chaincode/{{ $chaincode.name }} -n {{ $chaincode.name }} \
                                  -v {{ $.Values.chaincode.version }} -l {{ $.Values.chaincode.language }} -o {{ $orderer }}:7050"]

      volumeMounts:
        - mountPath: /etc/hyperledger/fabric/tls/
          name: peer-{{ $org.Name | lower }}-{{ $peer | lower }}-tls
        - mountPath: /etc/hyperledger/fabric/msp/
          name: peer-{{ $org.Name | lower }}-{{ $peer | lower }}-admin-msp
        - mountPath: /hlf_config/chaincode/
          name: chaincode-{{ $chaincode.name | lower }}
      
      env:
        - name: CORE_PEER_ADDRESS
          value: hlf-peer--{{ $org.Name | lower }}--{{ $peer | lower }}:7051
        - name: FABRIC_LOGGING_SPEC
          value: debug
        - name: CORE_PEER_LOCALMSPID
          value: {{ $org.Name }}MSP
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/tls/ca.crt

{{ end }} {{- /* peerIndex */ -}} 
{{ end }} {{- /* if org */ -}} 
{{ end }} {{- /* peer.Orgs */ -}}
{{ end }} {{- /* chaincode.orgs */ -}}
{{- end }} {{- /* if chaincode included */ -}}
{{ end }} {{- /* chaincodes */ -}}
{{ end }} {{- /* if flow.install.enabled */ -}}{{""}}

# leaf instantiate templates
{{- if $.Values.flow.instantiate.enabled }}
{{- range $i, $chaincode := .Values.network.chaincodes }}
{{- if or (not $.Values.flow.chaincode.include) (has $chaincode.name $.Values.flow.chaincode.include) }}
{{- range $channel := $chaincode.channels }}
{{- $orgName := index $channel.orgs 0 }}
{{- range $i, $org := $.Values.PeerOrgs }}

{{- if eq $orgName $org.Name }}

{{- $peerStartIndex := (not $org.Template.Start) | ternary 0 $org.Template.Start | int }}
{{- $peer := (printf "peer%s" ($peerStartIndex | toString)) }}

  - name: instantiate-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}--{{ $channel.name }}--{{ $org.Name }}--{{ $peer }}
    # chaincode: {{ $chaincode.name }}
    # channel: {{ $channel.name }}
    # org: {{ $org.Name }}
    # peer: {{ $peer }}
    inputs:
    retryStrategy:
      limit: {{ $.Values.retryCount }}
    container:
      image: hyperledger/fabric-peer:{{ $.Values.hyperledgerVersion }}
      command: ["sh", "-c", "peer chaincode instantiate -C {{ $channel.name }} -n {{ $chaincode.name }} -v {{ $.Values.chaincode.version }} -l {{ $.Values.chaincode.language }} -P \"{{ $channel.policy }}\" -o {{ $orderer }}:7050 -c '{\"Args\":[\"\"]}'"]

      volumeMounts:
        - mountPath: /etc/hyperledger/fabric/tls/
          name: peer-{{ $org.Name | lower }}-{{ $peer | lower }}-tls
        - mountPath: /etc/hyperledger/fabric/msp/
          name: peer-{{ $org.Name | lower }}-{{ $peer | lower }}-admin-msp
      
      env:
        - name: CORE_PEER_ADDRESS
          value: hlf-peer--{{ $org.Name | lower }}--{{ $peer | lower }}:7051
        - name: FABRIC_LOGGING_SPEC
          value: debug
        - name: CORE_PEER_LOCALMSPID
          value: {{ $org.Name }}MSP
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/tls/ca.crt

{{ end }} {{- /* if org */ -}} 
{{ end }} {{- /* peer.Orgs */ -}}
{{ end }} {{- /* chaincode.channels */ -}}
{{- end }} {{- /* if chaincode included */ -}}
{{ end }} {{- /* chaincodes */ -}}
{{ end }} {{- /* if flow.instantiate.enabled */ -}}{{""}}

# leaf upgrade templates
{{- if $.Values.flow.upgrade.enabled }}
{{- range $i, $chaincode := .Values.network.chaincodes }}
{{- if or (not $.Values.flow.chaincode.include) (has $chaincode.name $.Values.flow.chaincode.include) }}
{{- range $channel := $chaincode.channels }}
{{- $orgName := index $channel.orgs 0 }}
{{- range $i, $org := $.Values.PeerOrgs }}

{{- if eq $orgName $org.Name }}

{{- $peerStartIndex := (not $org.Template.Start) | ternary 0 $org.Template.Start | int }}
{{- $peer := (printf "peer%s" ($peerStartIndex | toString)) }}

  - name: upgrade-chaincode--{{ $chaincode.name }}-{{ $.Values.chaincode.version | replace "." "-" }}--{{ $channel.name }}--{{ $org.Name }}--{{ $peer }}
    # chaincode: {{ $chaincode.name }}
    # channel: {{ $channel.name }}
    # org: {{ $org.Name }}
    # peer: {{ $peer }}
    inputs:
    retryStrategy:
      limit: {{ $.Values.retryCount }}
    container:
      image: hyperledger/fabric-peer:{{ $.Values.hyperledgerVersion }}
      command: ["sh", "-c", "peer chaincode upgrade -C {{ $channel.name }} -n {{ $chaincode.name }} -v {{ $.Values.chaincode.version }} -l {{ $.Values.chaincode.language }} -P \"{{ $channel.policy }}\" -o {{ $orderer }}:7050 -c '{\"Args\":[\"\"]}'"]

      volumeMounts:
        - mountPath: /etc/hyperledger/fabric/tls/
          name: peer-{{ $org.Name | lower }}-{{ $peer | lower }}-tls
        - mountPath: /etc/hyperledger/fabric/msp/
          name: peer-{{ $org.Name | lower }}-{{ $peer | lower }}-admin-msp
      
      env:
        - name: CORE_PEER_ADDRESS
          value: hlf-peer--{{ $org.Name | lower }}--{{ $peer | lower }}:7051
        - name: FABRIC_LOGGING_SPEC
          value: debug
        - name: CORE_PEER_LOCALMSPID
          value: {{ $org.Name }}MSP
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/tls/ca.crt

{{ end }} {{- /* if org */ -}} 
{{ end }} {{- /* peer.Orgs */ -}}
{{ end }} {{- /* chaincode.channels */ -}}
{{- end }} {{- /* if chaincode included */ -}}
{{ end }} {{- /* chaincodes */ -}}
{{ end }} {{- /* if flow.upgrade.enabled */ -}}{{""}}

# leaf invoke templates
{{- if $.Values.flow.invoke.enabled }}
{{- range $i, $chaincode := .Values.network.chaincodes }}
{{- if or (not $.Values.flow.chaincode.include) (has $chaincode.name $.Values.flow.chaincode.include) }}
{{- range $channel := $chaincode.channels }}
{{- range $orgName := $channel.orgs }}
{{- range $i, $org := $.Values.PeerOrgs }}

{{- if eq $orgName $org.Name }}

{{- $peerStartIndex := (not $org.Template.Start) | ternary 0 $org.Template.Start | int }}
{{- range $peerIndex := untilStep $peerStartIndex (add $peerStartIndex $org.Template.Count | int) 1 }}
{{- $peer := (printf "peer%s" ($peerIndex | toString)) }}

  - name: invoke-chaincode--{{ $chaincode.name }}--{{ $channel.name }}--{{ $org.Name }}--{{ $peer }}
    # chaincode: {{ $chaincode.name }}
    # channel: {{ $channel.name }}
    # org: {{ $org.Name }}
    # peer: {{ $peer }}
    inputs:
    retryStrategy:
      limit: {{ $.Values.retryCount }}
    container:
      image: hyperledger/fabric-peer:{{ $.Values.hyperledgerVersion }}
      # chaincode is packed with tar, first extract it
      command: ["sh", "-c", "peer chaincode invoke -C {{ $channel.name }} -n {{ $chaincode.name }} -o {{ $orderer }}:7050 -c {{ $.Values.flow.invoke.function | replace "\"" "\\\"" | squote }}"]

      volumeMounts:
        - mountPath: /etc/hyperledger/fabric/tls/
          name: peer-{{ $org.Name | lower }}-{{ $peer | lower }}-tls
        - mountPath: /etc/hyperledger/fabric/msp/
          name: peer-{{ $org.Name | lower }}-{{ $peer | lower }}-admin-msp
      
      env:
        - name: CORE_PEER_ADDRESS
          value: hlf-peer--{{ $org.Name | lower }}--{{ $peer | lower }}:7051
        - name: FABRIC_LOGGING_SPEC
          value: debug
        - name: CORE_PEER_LOCALMSPID
          value: {{ $org.Name }}MSP
        - name: CORE_PEER_TLS_CERT_FILE
          value: /etc/hyperledger/fabric/tls/server.crt
        - name: CORE_PEER_TLS_KEY_FILE
          value: /etc/hyperledger/fabric/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /etc/hyperledger/fabric/tls/ca.crt

{{ end }} {{- /* peerIndex */ -}} 
{{ end }} {{- /* if org */ -}} 
{{ end }} {{- /* peer.Orgs */ -}}
{{ end }} {{- /* channel.orgs */ -}}
{{ end }} {{- /* chaincode.channels */ -}}
{{- end }} {{- /* if chaincode included */ -}}
{{ end }} {{- /* chaincodes */ -}}
{{ end }} {{- /* if flow.invoke.enabled */ -}}{{""}}